allowBuilds:
  esbuild: true
  mongodb-memory-server: true
minimumReleaseAgeExclude:
  - mongodb-memory-server-core@11.2.0
  - mongodb-memory-server@11.2.0
  - mongoose@9.6.3
onlyBuiltDependencies:
  - esbuild
  - mongodb-memory-server
