name: Deploy to Fly.io (server)

on:
  push:
    branches:
      - main
    paths:
      - 'packages/server/**'
      - '.github/workflows/server.yml'
jobs:
  deploy:
    name: Deploy to Fly.io (server)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy packages/server --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
